export const product = [
  // 🛋️ Living Room
  {
    id: 1,
    name: "Luxe Lounge Sofa",
    category: "Living Room",
    price: 235.99,
    discount: 20,
    image: "/images/luxe-lounge-sofa.png",
  },
  {
    id: 2,
    name: "Comfort Haven Sofa",
    category: "Living Room",
    price: 250.99,
    discount: 10,
    image: "/images/comfort-haven-sofa.png",
  },
  {
    id: 3,
    name: "Round Wicker Chair",
    category: "Living Room",
    price: 180.99,
    discount: 25,
    image: "/images/round-wicker-chair.png",
  },
  {
    id: 4,
    name: "Elegant Coffee Table",
    category: "Living Room",
    price: 120.49,
    discount: 15,
    image: "/images/elegant-coffee-table.png",
  },
  {
    id: 5,
    name: "Leather Recliner",
    category: "Living Room",
    price: 299.0,
    discount: 18,
    image: "/images/leather-recliner.png",
  },
  {
    id: 6,
    name: "Glass Top TV Stand",
    category: "Living Room",
    price: 145.75,
    discount: 12,
    image: "/images/glass-tv-stand.png",
  },

  // 🛏️ Bed Room
  {
    id: 7,
    name: "Velvet Ottoman",
    category: "Bed Room",
    price: 95.99,
    discount: 10,
    image: "/images/velvet-ottoman.png",
  },
  {
    id: 8,
    name: "Tufted Bed Frame",
    category: "Bed Room",
    price: 310.0,
    discount: 20,
    image: "/images/tufted-bed-frame.png",
  },
  {
    id: 9,
    name: "Wooden Nightstand",
    category: "Bed Room",
    price: 70.0,
    discount: 5,
    image: "/images/wooden-nightstand.png",
  },
  {
    id: 10,
    name: "King Size Mattress",
    category: "Bed Room",
    price: 450.0,
    discount: 30,
    image: "/images/king-mattress.png",
  },
  {
    id: 11,
    name: "Bedroom Lamp Set",
    category: "Bed Room",
    price: 60.0,
    discount: 10,
    image: "/images/bedroom-lamps.png",
  },
  {
    id: 12,
    name: "Sliding Door Wardrobe",
    category: "Bed Room",
    price: 370.0,
    discount: 22,
    image: "/images/wardrobe.png",
  },

  // 🍽️ Dining Room
  {
    id: 13,
    name: "Modern Dining Table",
    category: "Dining Room",
    price: 400.0,
    discount: 18,
    image: "/images/dining-table.png",
  },
  {
    id: 14,
    name: "Set of 4 Dining Chairs",
    category: "Dining Room",
    price: 220.0,
    discount: 10,
    image: "/images/dining-chairs.png",
  },
  {
    id: 15,
    name: "Crockery Cabinet",
    category: "Dining Room",
    price: 320.0,
    discount: 12,
    image: "/images/crockery-cabinet.png",
  },
  {
    id: 16,
    name: "Wooden Sideboard",
    category: "Dining Room",
    price: 280.0,
    discount: 20,
    image: "/images/sideboard.png",
  },
  {
    id: 17,
    name: "Dining Bench",
    category: "Dining Room",
    price: 160.0,
    discount: 8,
    image: "/images/dining-bench.png",
  },
  {
    id: 18,
    name: "Table Runner Set",
    category: "Dining Room",
    price: 45.0,
    discount: 10,
    image: "/images/table-runner.png",
  },

  // 🌿 Outdoor
  {
    id: 19,
    name: "Outdoor Swing Chair",
    category: "Outdoor",
    price: 275.0,
    discount: 20,
    image: "/images/swing-chair.png",
  },
  {
    id: 20,
    name: "Garden Table Set",
    category: "Outdoor",
    price: 390.0,
    discount: 18,
    image: "/images/garden-table-set.png",
  },
  {
    id: 21,
    name: "Patio Umbrella",
    category: "Outdoor",
    price: 110.0,
    discount: 12,
    image: "/images/patio-umbrella.png",
  },
  {
    id: 22,
    name: "Outdoor Bean Bag",
    category: "Outdoor",
    price: 95.0,
    discount: 10,
    image: "/images/outdoor-beanbag.png",
  },
  {
    id: 23,
    name: "BBQ Grill Stand",
    category: "Outdoor",
    price: 250.0,
    discount: 15,
    image: "/images/bbq-grill.png",
  },
  {
    id: 24,
    name: "Foldable Camping Chair",
    category: "Outdoor",
    price: 65.0,
    discount: 8,
    image: "/images/camping-chair.png",
  },

  // 🪴 Indoor
  {
    id: 25,
    name: "Indoor Planter Set",
    category: "Indoor",
    price: 55.0,
    discount: 10,
    image: "/images/indoor-planters.png",
  },
  {
    id: 26,
    name: "Aroma Diffuser Lamp",
    category: "Indoor",
    price: 40.0,
    discount: 12,
    image: "/images/aroma-diffuser.png",
  },
  {
    id: 27,
    name: "Wall Hanging Shelf",
    category: "Indoor",
    price: 65.0,
    discount: 15,
    image: "/images/wall-shelf.png",
  },
  {
    id: 28,
    name: "Bean Bag Chair",
    category: "Indoor",
    price: 125.0,
    discount: 20,
    image: "/images/bean-bag.png",
  },
  {
    id: 29,
    name: "Indoor Hammock",
    category: "Indoor",
    price: 160.0,
    discount: 18,
    image: "/images/indoor-hammock.png",
  },
  {
    id: 30,
    name: "Decorative Lamp Set",
    category: "Indoor",
    price: 90.0,
    discount: 14,
    image: "/images/decor-lamp.png",
  },
];
